### ISSUE TITLE
准备开新项目了吗？

### ISSUE THREAD

**Issue by EvaGalois** [hiroi-sora/Umi-OCR_runtime_windows#1]
我希望能了解到你这个项目的具体作用。

**Comment by hiroi-sora** [comment]
这里作为Umi-OCR的子仓库使用，放置windows运行环境及一些不常更新但是重要的二进制文件。这样主仓库可以只放置跨平台源代码，便于管理，减少体积，加快git同步速度。

我正在构建的 Umi-OCR 项目结构：
- [Umi-OCR](https://github.com/hiroi-sora/Umi-OCR) - 主仓库
- [Umi-OCR_plugins](https://github.com/hiroi-sora/Umi-OCR_plugins) - 插件仓库
- [Umi-OCR_runtime_windows](https://github.com/hiroi-sora/Umi-OCR_runtime_windows) - win运行环境
- Umi-OCR_runtime_linux - Linux运行环境
- Umi-OCR_runtime_macos - .....
