### ISSUE TITLE
How do you make `Umi-OCR.exe`?

### ISSUE THREAD

**Issue by martianzhang** [hiroi-sora/Umi-OCR_runtime_windows#3]
`Umi-OCR.exe` is the starter, how do you make this program and where can I find its source code?

**Comment by hiroi-sora** [comment]
The source  code is [here](https://github.com/hiroi-sora/Umi-OCR_runtime_windows/tree/main/PyStand_for_UmiOCR).
Based on [this project](https://github.com/skywind3000/PyStand), I made some modifications.

**Comment by hiroi-sora** [comment]
If you're interested in PyStand, here are some more detailed [documents](https://github.com/hiroi-sora/PyStand-Sora).
